trigger: none

# pool: default
pool: 
  name: default
  demands: agent.name -equals e-zaslavsky
  

steps:
- script: |
    pwd
  displayName: 'print working directory'

- script: |
    ls -la 
  displayName: 'list files'

- script: |
    echo $(Agent.BuildDirectory)
  displayName: 'echo debug'