trigger: none

# pool: default
pool: 
  name: default
  demands: e-zaslavsky
  

steps:
- script: |
    pwd
  displayName: 'print working directory'

- script: |
    ls -la 
  displayName: 'list files'
