trigger: none

# pool: default
pool: 
  name: default
  demands: agent.name -equals e-zaslavsky
  

steps:
- script: |
    pwd
  displayName: 'print working directory'

- script: |
    ls -la 
  displayName: 'list files'

# - bash: echo Value of Agent.BuildDirectory = $BLA
#   env:
#     BLA: $(Agent.BuildDirectory)
#   displayName: 'Print value of $(Agent.BuildDirectory)'

- bash: echo Value of Agent.BuildDirectory = $(Agent.BuildDirectory)