trigger: none

# pool: default
pool:
  name: default
  demands: agent.name -equals e-zaslavsky

steps:
- script: |
    pwd
  displayName: 'print working directory'

- script: |
    ls -la
  displayName: 'list files'

# - bash: echo Value of Agent.BuildDirectory = $BLA
#   env:
#     BLA: $(Agent.BuildDirectory)
#   displayName: 'Agent.BuildDirectory = $(Agent.BuildDirectory)'
- bash: echo Value of Agent.BuildDirectory = $(Agent.BuildDirectory)
  displayName: 'Agent.BuildDirectory = $(Agent.BuildDirectory)'

- bash: echo Value of Build.SourcesDirectory = $(Build.SourcesDirectory)
  displayName: 'Build.SourcesDirectory = $(Build.SourcesDirectory)'

- bash: echo Value of Build.SourcesDirectory = $(Build.SourcesDirectory)
  displayName: 'Build.SourcesDirectory = $(Build.SourcesDirectory)'

- bash: echo Value of Build.BinariesDirectory = $(Build.BinariesDirectory)
  displayName: 'Build.BinariesDirectory = $(Build.BinariesDirectory)'