name: Check Reviewer Approval

on:
  workflow_run:
    workflows: ["Enforce Reviewer Assignment"]  # Название основного воркфлоу
    types:
      - completed  # Запуск после завершения основного воркфлоу

jobs:
  check-approval:
    runs-on: ubuntu-latest

    env:
      RELEASE_REVIEWER: ThirdFimmiUser  # Определяем рецензента

    steps:
      - name: Check if Reviewer Approved
        if: ${{ vars.RELEASE_MODE == 'true' }}
        run: |
          set -x
          PR_NUMBER="${{ github.event.workflow_run.head_branch }}"
          
          # Проверка, одобрен ли PR нужным рецензентом
          echo "Checking if $RELEASE_REVIEWER has approved the PR..."
          REVIEWS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews)

          # Проверяем, есть ли аппрув от RELEASE_REVIEWER
          if [[ "$REVIEWS" == *"$RELEASE_REVIEWER"* && "$REVIEWS" == *"APPROVED"* ]]; then
            echo "$RELEASE_REVIEWER has approved the PR."
          else
            echo "$RELEASE_REVIEWER has not approved the PR."
            echo "Approval from $RELEASE_REVIEWER is required before merging."
            exit 1  # Фейлим чек, если аппрува нет
          fi
