name: Enforce Required Reviews

on:
  pull_request:
    types: [opened, synchronize, review_requested, review_submitted]

jobs:
  enforce-reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Check if ccu2-release-reviewers is assigned
        run: |
          # Получаем список назначенных ревьюверов
          ASSIGNED_REVIEWERS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers)

          echo ASSIGNED_REVIEWERS = $ASSIGNED_REVIEWERS
          
          # # Проверяем, назначена ли команда ccu2-release-reviewers
          # if echo "$ASSIGNED_REVIEWERS" | grep -q "ccu2-release-reviewers"; then
          #   echo "ccu2-release-reviewers is assigned"

          #   # Получаем статус ревью команды ccu2-release-reviewers
          #   REVIEWS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          #     https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews)

          #   # Проверяем, есть ли аппрув от ccu2-release-reviewers
          #   if echo "$REVIEWS" | grep -q '"state": "APPROVED"'; then
          #     echo "ccu2-release-reviewers has approved the PR"
          #   else
          #     echo "ccu2-release-reviewers has not approved the PR"
          #     exit 1  # Прерываем выполнение с ошибкой, что приведет к фейлу чека
          #   fi
          # else
          #   echo "ccu2-release-reviewers is not assigned, skipping check"
          # fi
