name: Enforce Required Reviews in Release Mode

on:
  pull_request:
    types: [opened, synchronize, review_requested, review_submitted]

jobs:
  enforce-reviews:
    runs-on: ubuntu-latest

    env:
      RELEASE_REVIEWER: ThirdFimmiUser  # Define the user as a variable

    steps:
      - name: Check if the user is already a reviewer and add if necessary
        run: |
          # Get the list of assigned reviewers
          ASSIGNED_REVIEWERS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers)
          
          echo ASSIGNED_REVIEWERS = $ASSIGNED_REVIEWERS
