name: Enforce Reviewer Assignment

# Включаем необходимые события для обработки PR
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  pull_request_review:
    types: [submitted]


jobs:
  enforce-reviewer:
    runs-on: ubuntu-latest

    env:
      RELEASE_REVIEWER: ThirdFimmiUser  # Определяем рецензента

    steps:
      - name: Ensure Release Reviewer is Assigned
        if: ${{ vars.RELEASE_MODE == 'true' }}
        run: |
          set -x
          echo "env.RELEASE_MODE = ${{ vars.RELEASE_MODE }}"
          echo "Release mode enabled: ${{ vars.RELEASE_MODE == 'true' }}"
          
          PR_NUMBER="${{ github.event.pull_request.number }}"
          
          # Получаем список назначенных рецензентов
          ASSIGNED_REVIEWERS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers)

          # Проверяем, назначен ли RELEASE_REVIEWER
          if [[ "$ASSIGNED_REVIEWERS" == *"$RELEASE_REVIEWER"* ]]; then
            echo "$RELEASE_REVIEWER is already a reviewer."
          else
            echo "$RELEASE_REVIEWER is not a reviewer yet, adding now."

            # Добавляем рецензента
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers \
              -d "{\"reviewers\":[\"$RELEASE_REVIEWER\"]}"

            # Короткая пауза для завершения добавления рецензента
            sleep 3
          fi
